platform :ios, '10.0'


def shared_pods
    use_frameworks!
    pod 'AFNetworking', '~> 3.1.0'
    pod 'CocoaAsyncSocket', '~> 7.6.1'
    pod 'ProtocolBuffers-Swift', '4.0.1'
end

target "IMSocket"  do
    shared_pods
end


target "TodayTest" do
    shared_pods
end
